title: <p align="center"> Sagarika Bhadra </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://github.com/Sa2019Si">GitHub</a>
  
  
  <br>   
  I am working as a Automation Consultant in BFS Domain for 11 years
  <br>
  </p>



theme: jekyll-theme-minimal
